name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4

    # Install and build backend
    - name: Set up Node.js for Backend
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: ./backend/package-lock.json   # Pointing to backend's lock file
    - name: Install dependencies for Backend
      working-directory: ./backend
      run: npm install
    - name: Build Backend
      working-directory: ./backend
      run: npm run build --if-present

    # Install and build frontend
    - name: Set up Node.js for Frontend
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: ./front/package-lock.json  # Pointing to frontend's lock file
    - name: Install dependencies for Frontend
      working-directory: ./front
      run: npm install
    - name: Build Frontend
      working-directory: ./front
      run: npm run build --if-present
